server:
  port: ":9999"
  tcp:  ":50051"
  language: "zh"
  jwt: "/*26vioevIJVowae)^%^&57/*-++++==="

#设置缓存前缀和时长，以分钟计时
captcha:
    prefix: "captcha"
    expire: 3
#etcd
etcd: [ "192.168.245.22:2379" ]

#mysql连接配置
mysql:
  username: "root"
  password: "123456"
  host: "192.168.245.22"
  port: "3306"
  database: "test_go"
  charset: "utf8mb4"
  timeout: "10"

postgresql:
  host:
  user:
  password:
  port:
  dbname:
  sslmode:
  TimeZone:
#casbin
casbin:
  type: mysql
  username: "root"
  password: "123456"
  host: "192.168.245.22"
  port: "3306"
  database: "casbin"
  exist: false

#rabbitmq example:"amqp://guest:guest@192.168.245.33:5672/"
rabbitmq:
  url: "amqp://guest:guest@192.168.245.33:5672/"
  username: "guest"
  password: "guest"
  host: "192.168.245.33"
  port: "5672"


#kafka
kafka: [ "192.168.245.22:9092" ]

click:
  host: "192.168.245.22"
  port: 8123
  name: "root"
  password: "123456"

#日志存放位置，以及名称限制
log:
  logPath: "src/config/logs"
  linkName: "src/config/logs/latest.log"

